services:
  aap:
    runtime: sysbox-runc
    labels:
      traefik.enable: false
    user: root
    image: antonio24073/aapanel:ubuntu-22-04-sysbox-apache
    container_name: aapanel
    ports: 
      - ${AAP_PORT}:7800
      - ${FTP_PORT}:21
      - ${SSH_PORT}:22
      - 443:443
      - 80:80
      - ${PMA_PORT}:888
      - ${PMAS_PORT}:887

      # mail ports:
      # - 587:587
      # - 465:465
      # - 25:25
      # - 995:995
      # - 110:110
      # - 993:993
      # - 143:143

    volumes:
      - ./vol/root:/root
      - ./vol/home/${LINUX_USER_NAME}:/home/${LINUX_USER_NAME}
      - ./vol/www/wwwroot:/www/wwwroot
      - ./vol/www/server/data:/www/server/data
      - ./vol/www/server/panel/vhost:/www/server/panel/vhost
      - ./vol/www/server/panel/data:/www/server/panel/data
      - ./vol/www/server/pass:/www/server/pass
      - ./vol/www/wwwlogs:/www/wwwlogs
      - ./vol/www/backup:/www/backup
      - ./vol/www/vmail:/www/vmail
      - ./vol/provision/entrypoint:/provision/entrypoint
      - ./vol/etc/resolv.conf:/etc/resolv.conf
      - ./vol/etc/hosts:/etc/hosts
      - ./vol/www/server/python_manager/versions:/www/server/python_manager/versions
      - ./vol/www/server/python_manager/panel/plugin/pythonmamager/config.json:/www/server/panel/plugin/pythonmamager/config.json
      - ./vol/www/server/panel/plugin/pgsql_manager_dbuser_info.json:/www/server/panel/plugin/pgsql_manager_dbuser_info.json
      - ./vol/www/server/pgsql:/www/server/pgsql
      - ./vol/www/server/nodejs:/www/server/nodejs

      # if you do not use docker sysbox enable this:
      # - /var/run/docker.sock:/var/run/docker.sock:ro

    env_file:
      - ./.env
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    ulimits:
      nofile:
        soft: 1024
        hard: 1048576
  wt:
    container_name: aapanel_wt
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 1800

    